# Generated by Django 3.2.9 on 2021-12-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0002_rename_neighbourhood_profile_nextdoor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='neighbourhood',
            new_name='nextdoor',
        ),
    ]
