# Generated by Django 3.2.9 on 2021-12-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0003_rename_neighbourhood_contact_nextdoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
