# Generated by Django 3.2.9 on 2021-12-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0006_rename_descriptions_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
